// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	kubecon_io_v1 "k8s.io/kubecon/pkg/apis/kubecon.io/v1"
	versioned "k8s.io/kubecon/pkg/client/clientset/versioned"
	internalinterfaces "k8s.io/kubecon/pkg/client/informers/externalversions/internalinterfaces"
	v1 "k8s.io/kubecon/pkg/client/listers/kubecon.io/v1"
)

// SessionInformer provides access to a shared informer and lister for
// Sessions.
type SessionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SessionLister
}

type sessionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSessionInformer constructs a new informer for Session type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSessionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSessionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSessionInformer constructs a new informer for Session type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSessionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeconV1().Sessions(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeconV1().Sessions(namespace).Watch(options)
			},
		},
		&kubecon_io_v1.Session{},
		resyncPeriod,
		indexers,
	)
}

func (f *sessionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSessionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sessionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubecon_io_v1.Session{}, f.defaultInformer)
}

func (f *sessionInformer) Lister() v1.SessionLister {
	return v1.NewSessionLister(f.Informer().GetIndexer())
}
