// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
	v1 "k8s.io/kubecon/pkg/apis/kubecon.io/v1"
	"k8s.io/kubecon/pkg/client/clientset/versioned/scheme"
)

type KubeconV1Interface interface {
	RESTClient() rest.Interface
	SessionsGetter
}

// KubeconV1Client is used to interact with features provided by the kubecon.io group.
type KubeconV1Client struct {
	restClient rest.Interface
}

func (c *KubeconV1Client) Sessions(namespace string) SessionInterface {
	return newSessions(c, namespace)
}

// NewForConfig creates a new KubeconV1Client for the given config.
func NewForConfig(c *rest.Config) (*KubeconV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &KubeconV1Client{client}, nil
}

// NewForConfigOrDie creates a new KubeconV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *KubeconV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new KubeconV1Client for the given RESTClient.
func New(c rest.Interface) *KubeconV1Client {
	return &KubeconV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *KubeconV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
