// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "k8s.io/kubecon/pkg/apis/kubecon.io/v1"
	scheme "k8s.io/kubecon/pkg/client/clientset/versioned/scheme"
)

// SessionsGetter has a method to return a SessionInterface.
// A group's client should implement this interface.
type SessionsGetter interface {
	Sessions(namespace string) SessionInterface
}

// SessionInterface has methods to work with Session resources.
type SessionInterface interface {
	Create(*v1.Session) (*v1.Session, error)
	Update(*v1.Session) (*v1.Session, error)
	UpdateStatus(*v1.Session) (*v1.Session, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.Session, error)
	List(opts meta_v1.ListOptions) (*v1.SessionList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Session, err error)
	SessionExpansion
}

// sessions implements SessionInterface
type sessions struct {
	client rest.Interface
	ns     string
}

// newSessions returns a Sessions
func newSessions(c *KubeconV1Client, namespace string) *sessions {
	return &sessions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the session, and returns the corresponding session object, and an error if there is any.
func (c *sessions) Get(name string, options meta_v1.GetOptions) (result *v1.Session, err error) {
	result = &v1.Session{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sessions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Sessions that match those selectors.
func (c *sessions) List(opts meta_v1.ListOptions) (result *v1.SessionList, err error) {
	result = &v1.SessionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sessions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sessions.
func (c *sessions) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sessions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a session and creates it.  Returns the server's representation of the session, and an error, if there is any.
func (c *sessions) Create(session *v1.Session) (result *v1.Session, err error) {
	result = &v1.Session{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sessions").
		Body(session).
		Do().
		Into(result)
	return
}

// Update takes the representation of a session and updates it. Returns the server's representation of the session, and an error, if there is any.
func (c *sessions) Update(session *v1.Session) (result *v1.Session, err error) {
	result = &v1.Session{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sessions").
		Name(session.Name).
		Body(session).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *sessions) UpdateStatus(session *v1.Session) (result *v1.Session, err error) {
	result = &v1.Session{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sessions").
		Name(session.Name).
		SubResource("status").
		Body(session).
		Do().
		Into(result)
	return
}

// Delete takes name of the session and deletes it. Returns an error if one occurs.
func (c *sessions) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sessions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sessions) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sessions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched session.
func (c *sessions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Session, err error) {
	result = &v1.Session{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sessions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
