// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1 "k8s.io/kubecon/pkg/client/clientset/versioned/typed/kubecon.io/v1"
)

type FakeKubeconV1 struct {
	*testing.Fake
}

func (c *FakeKubeconV1) Sessions(namespace string) v1.SessionInterface {
	return &FakeSessions{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKubeconV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
